### ISSUE TITLE
Doesn't work if page pinned to the side

### ISSUE THREAD

**Issue by lillianhorin** [denolehov/obsidian-url-into-selection#1]
OS: Windows 10
Obsidian Version: 0.9.11

This plugin works great when a page I'm working on is one of the main pages. But if the page I'm working on is pinned to the side, it simply pastes the links. (i.e. `ctrl + shift + v` acts like `ctrl + v`). An image is shown below of what I mean by having the page pinned to the side. 

![image](https://user-images.githubusercontent.com/24489520/98072653-8006e400-1e34-11eb-8efe-e90a7ac52c05.png)

**Comment by denolehov** [comment]
Interesting, I will take a look at this and let you know!

**Comment by denolehov** [comment]
@lillianhorin i've looked into the issue, turns out it's impossible to programmatically manipulate editor of a page that is pinned to the sidebar, this is a restriction that Obsidian developers looking to lift soon.

I will keep this issue open as a reminder for myself to revisit this in some of the future updates and see if it works.

**Comment by lillianhorin** [comment]
@denolehov Great, thank you so much for the update!

**Comment by AidenLx** [comment]
Can be closed as [9d76f2](https://github.com/denolehov/obsidian-url-into-selection/pull/11/commits/9d76f2fb36dcf5bfc228bf6c2102fcb995e9a859) bind url-to selection to every CodeMirror instance's paste event. (Command/hotkey still doesn't work, unfortunately)

**Comment by denolehov** [comment]
@lillianhorin as @AidenLx mentioned, this works now with the regular `ctrl + V` command! If you're still using this, please update the plugin :)
