### ISSUE TITLE
Appreciation post and design questions

### ISSUE THREAD

**Issue by larizzatg** [denolehov/obsidian-url-into-selection#10]
Hi @denolehov,

I'm on a journey to learn typescript while developing plugins because obsidian doesn't have a lot of doc about creating plugins yet, what I'm trying to learn with the work of others, writing line by line each plugin available (locally in my machine) and documenting my learnings in obsidian :D 

With your plugin, I learned to create commands with hotkeys, some of the code mirror API (like getting the cursor position and updating the selected element), and what is an active leaf and different types of leaf.

I had a question though, I tried to replicate using electron but couldn't due to an error in npm install (every time I tried :F) so I use the clipboard web API of the navigator, is there a reason why you use the electron API instead.

Would love to hear back from you, thanks for the contribution :D

**Comment by denolehov** [comment]
Hey @larizzatg, I am glad you find this plugin and its code useful! :)

Interestingly enough, that's exactly the way I was learning TypeScript as well! 😄 

Re. clipboard and electron API: it's used mainly because electron provides a nice abstraction over clipboard functionality which is platform-agnostic. I would assume that clipboard web API could do the trick, but I am pretty sure it bears some limitations with it.

What error you're getting by the way? Let's try to figure it out?

**Comment by AidenLx** [comment]
I believe this should no longer the problem since type defenition`@types/electron` is used in favor of full `electron` library, which is used to develop electron apps from [b00aa1](https://github.com/denolehov/obsidian-url-into-selection/pull/11/commits/b00aa10de2bb28dd5a277555cc160a7760812e38). Also, the difference is explained [here](https://github.com/denolehov/obsidian-url-into-selection/pull/14#issue-619309233)
