### ISSUE TITLE
Customize the Hotkey

### ISSUE THREAD

**Issue by Overload119** [denolehov/obsidian-url-into-selection#4]

**Comment by denolehov** [comment]
Hey @Overload119, what hotkey customization you feel lacking?

**Comment by Cito** [comment]
Maybe you should mention in the description that the hotkey can be customized just like any other built-in hotkey in Obsidian. People might expect the customization under "Plugin options" otherwise.

Btw, on a Windows keyboard, Shift-Insert is a great alternative to Ctrl-Alt-V.

**Comment by kankaristo** [comment]
`Ctrl+Shift+V` is a bad default, IMO. It's already the keybinding for "paste without formatting".

For example, if you copy some **bold text** (e.g. from your browser) and:
- paste it into Obsidian with `Ctrl+V`, it's pasted as `**bold text**` (the bold text is converted to Markdown formatting)
- paste it into Obisidan with `Ctrl+Shift+V`, it's pasted as `bold text` (the text is copied as is, as plain text)

The default keybinding from this extension breaks the above behavior. I'm not sure if `Cmd+Shift+V` does the same on Mac, but it's a common keybinding on Windows and Linux (works in most text editors).

**Comment by yangwao** [comment]
Doesn't work for me on OSX with ```Ctrl+Shift+V``` 🤔

**Comment by Overload119** [comment]
Closing this issue since you can customize any hotkey with Obsidian's UI and I was just not aware of it.

**Comment by Cito** [comment]
This issue should either be re-opened, or these new issues should be opend, since these problems still exist:
- It should be mentioned in the description that the hotkey can be customized just like any other built-in hotkey in Obsidian, since people may expect the customization under "Plugin options".
- The default key should not be `Ctrl+Shift-V` because this is now be used by Obsidian for "paste plain text".

**Comment by denolehov** [comment]
The default hotkey is `ctrl+V` since v1.5.0 \o/

**Comment by yangwao** [comment]
So does mean don't need to use a plugin anymore?
