### ISSUE TITLE
Overrides default "Paste as text" and does not have a way to resolve this conflict

### ISSUE THREAD

**Issue by gavvvr** [denolehov/obsidian-url-into-selection#9]
I do not know since what version, but Obsidian's Paste action (Cmd+V) is now smart. If I copy a link, it will create me a link with a text taken from page heading. Or if I copy a clickable text, Obsidian will preserve the link. Sometimes I just want to paste something as a raw text from my clipboard. And there is a **Cmd+Shift+V** for this:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/1719646/107850513-09ef2180-6e14-11eb-8c6f-d6ab951d4497.png">

But with this plugin the default shortcut does not work and I have to Right-click and use the above menu to paste raw text.
I like this plugin and still want to use it, but I would like to have a way to resolve the conflict with a default Cmd+Shift+V behavior. 
Possible solution: if no text is selected by cursor, preserve the original behavior

**Comment by Cito** [comment]
@gavvvr To resolve the conflict, you can change the hotkey for this add-on like any other hotkey.

But I think this should also be fixed in this add-on:
1. Add a note about how to change the hotkey in the docs
2. Change the default hotkey so that his conflict does not apper

See also issue #4 which I think should be reopened.

**Comment by denolehov** [comment]
Added a note regarding hotkey usage.

I will not change the default hotkey, since the plugin has been out for a while and people got used to it.

Thank you for raising this issue! :slightly_smiling_face:
